### ISSUE TITLE
Travis CI pytest Fails

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/faradayio#10]
@reillyeon and @rhjdjong Maybe you can provide insight into this. My local copy of this repo works fine with `pytest` and passes:
![image](https://user-images.githubusercontent.com/331540/34286497-d84c9616-e695-11e7-99ee-b7a05f23b70e.png)

However it fails on Travis CI:
![image](https://user-images.githubusercontent.com/331540/34286525-091ca010-e696-11e7-82a7-c8ee0b0f2a32.png)
https://travis-ci.org/kb1lqc/faradayio/builds/320068367

This could be related to the fact that the latest `sliplib` on pypi is V0.0.1 and that is unuseable so I clone the latest GitHub repo of the project  and `pip install SlipLib` in `travis.yml`.

```
language: python
python:
  - "3.5"

# Install dependencies
install:
  - pip install -r requirements.txt
  - git clone https://github.com/rhjdjong/SlipLib.git
  - pip install SlipLib

# Run tests
script:
  - "flake8 --exclude .venv/,docs/,SlipLib/ ."
  - pytest tests/
```

This however may cause sliplib to not work right? Thoughts?

**Comment by rhjdjong** [comment]
Pip install as you use it here fetches sliplib from PyPI. To install from the local copy you need additional arguments. I'm writing this from my cell phone, so I can not easily look up the exact syntax. My plan is to use the Christmas break to sync  sliplib on both GitHub and PyPI to the current version that lives on my home PC. Cheers, Ruud.

**Comment by kb1lqc** [comment]
Thanks @rhjdjong ! Looking forward to it. If you want some help let me know if there are some easy items I can help with so you can focus on the main things. Your library so far looks really really useful for what we're doing!

**Comment by kb1lqc** [comment]
The [latest build](https://travis-ci.org/kb1lqc/faradayio/builds/332164188) works! This implements fixes from #17 and #18. However, it does skip the TUN testing per the output

```
The command "pytest --ignore=tests/test_tun.py tests/" exited with 0.
```

Therefore this line in `.travis.yml` should be removed and the build should be repeated.

**Comment by kb1lqc** [comment]
I've removed the extra configuration that allows the entire codebase to be tested. However, I cannot get the `python-pytun` to test since we need sudo priviledges.

https://travis-ci.org/kb1lqc/faradayio/builds/332181892

I tried to go about adding a sudo user but this didn't seem to work. I kept being told that the installed modules in python were not present which is indicative of the new user having a different python environment than that the `.travis.yml` installs with pip.

https://docs.travis-ci.com/user/reference/trusty/#Group-membership

Any ideas to allow sudo use of `python-pytest` on Travis-CI @hdkmike @reillyeon ?

**Comment by kb1lqc** [comment]
I keep getting the following error when trying to run `pytest` as sudo.
```
The command "sudo python3 -m pytest tests/" exited with 1.
```

Putting this on the backburner and I'm going to disable TUN testing on Travis-CI for now (but test it locally).

**Comment by kb1lqc** [comment]
Confirmed that by disabling the TUN tests and not running `sudo` on Travis CI I can move on for now. This does need to get addressed! @reillyeon @hdkmike suggestions welcomed!

https://travis-ci.org/kb1lqc/faradayio/builds/333141540

**Comment by herrold** [comment]
saw the tweet -- looking

**Comment by herrold** [comment]
> sudo python3 -m pytest tests/

Please do this:

1. Add a otherwise unused userid to the test environment
2. for that userid only, amend /etc/sudoers to have a line:

From: man 5 sudoers

```
 For example:

       ray     rushmore = NOPASSWD: /bin/kill, /bin/ls, /usr/bin/lprm

       would allow the user ray to run /bin/kill, /bin/ls, and /usr/bin/lprm
       as root on the machine rushmore without authenticating himself
```

Obviously substitute 'ray' with the userid added at step 1 ; substitute ALL for rushmore ; and
add the fully qualified path to the testing script, for the three listed in the man page example.

Query: you are running the bare command without a wrapping shell to set up, say: umask and PATH ... is this in play?

**Comment by kb1lqc** [comment]
@herrold how do I do this with `travis.yml`? I am lost. Are we simply talking Linux commands?

```
script:
- sudo adduser michael
- sudo usermod -aG sudo michael
```

Or are we doing a little more of what you were talking about in the `travis.yml`?
```
script:
- sudo adduser michael
- "michael    ALL = NOPASSWD: /<path to pytest>" >> /etc/sudoers
```

**Comment by reillyeon** [comment]
Yes, however by default Travis CI has switched to using containers that do not give you sudo privileged. You will need to update `.travis.yml` to one of the [distributions](https://docs.travis-ci.com/user/reference/overview/) that support it.

**Comment by kb1lqc** [comment]
@reillyeon I thought I had tried that. I'll have to try again. My original attempt used:

```
sudo: required
dist: trusty
```
To my knowledge this should have worked but I am pretty darn sure I as seeing the `pytest not found` error here.

**Comment by kb1lqc** [comment]
WHOA it worked @herrold @reillyeon https://travis-ci.org/kb1lqc/faradayio/builds/334215801

I added the standard Travis-CI distro and sudo configs as I had tried before:
```
sudo: required
dist: trusty
```

Then I iterated until I realized I needed to directly call `pytest` from it's virtual environment:
```
  - sudo ~/virtualenv/python3.5/bin/pytest tests/
```

Makes me wonder if I should call `flake8` directly too.

**Comment by kb1lqc** [comment]
Closing as @herrold and @reillyeon nailed the fix for this. SUPER THANKS!

Completed https://travis-ci.org/kb1lqc/faradayio/builds/334219476 successfully testing the TUN and SLIP code on Travis CI! @kb1lqd

**Comment by herrold** [comment]
neat stuff --- systematic debugging, and progressive error elimination, ftw
