### ISSUE TITLE
Faraday TUN Adapter

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/faradayio#13]
Documenting TUN adapter development here. Thanks to @hdkmike we have a nice reference to work from!

Reference: https://github.com/hdkmike/simple-tuntap

**Comment by kb1lqc** [comment]
Planning for IP Addresses I came across [this nice reference website](http://www.arrowmail.co.uk/articles/iprange.aspx).

Since Faraday radios may one day be connected over some sort of VPN backbone I suspect we want to start off assuming more than 200 may be connected together. Therefore I will use the 10.0.0.0 range IP space.

## 10.0.0.0 IP Address Subnets
Using [this nifty calculator](http://www.subnet-calculator.com/subnet.php?net_class=A) I decided to plan for 65,534 IP addresses which seems more than sufficient for now. Maybe one day I'll regret this decision. Oh well.

This allows 256 subnets and 65,534 devices per subnet for a maximum of 16,776,704 IP addresses total. Seems legit and if we ever get there with Faraday it will have been a massive success so also OK with this limitation ;)

![image](https://user-images.githubusercontent.com/331540/34321590-6d24671e-e7c7-11e7-8454-bc8df18d5a41.png)

Let's set the defaults to
- IP Address: 10.0.0.1
- Subnet Mask: 255.255.0.0

I need to figure out what/if the destination address `dstaddr` in `pytun` should be if needed. Must learn more about the peer to peer networking scheem of TUN adapters.

**Comment by kb1lqc** [comment]
Hey @hdkmike what's up with the [Routing](https://github.com/hdkmike/simple-tuntap#routing) section of your TUN adapter? What is the function. Is this what is forwarding from the TUN to the Internet?

**Comment by kb1lqc** [comment]
Chatted with @hdkmike and have some notes from our discussion that will hopefully clarify a few items in the TUN adapter effort:

Using my configuration shown above the following is true/thought to be...

- [ ] 10.0.1.0 may not be valid for /24 CIDR configuration though it is valid for /16 CIDR
- [ ] 10.0.0.0 is the "network"
- [ ] May want to shorten netmask
- [ ] 10.0.1.0 is the "sender" address, data sent here won't end up in the network buffer
- [ ] Must route into the tunnel or data won't be buffered which means use a destination address and send to that!
- [ ] Make IP a /32 to cut it down?
- [ ] Destination IP adds a Faraday radio at the other end of the "tunnel" which forces data into the Tunnel and is a peer to peer connection. Not scalable but it's a start.

**Comment by kb1lqc** [comment]
Noting that to run pytest with virtualenv and the TUN adapter you need to be sudo (at least for now). This requires you to manually call up the virtualenv python binary!

https://askubuntu.com/questions/234758/how-to-use-a-python-virtualenv-with-sudo

**Comment by kb1lqc** [comment]
Changed the IP address and CIDR to 10.0.0.1/24 as shown below:
![image](https://user-images.githubusercontent.com/331540/34550974-41845a22-f0ca-11e7-99ee-bc6decbb41a4.png)
![image](https://user-images.githubusercontent.com/331540/34550977-4e9d013c-f0ca-11e7-9985-8ceb2bdf3786.png)

I also updated the destination address in the Faraday TUN to be 10.0.0.2 and changed the unit test to check for all new configurations.

**Comment by kb1lqc** [comment]
I can see IP packets traveling over the TUN with a tun.read() call! now I need to parse IP packets to verify they are good for the unit test. It appears `scapy` is good to use. However, tricky for installing with python 3 since the instructions aren't on their documentation!

https://stackoverflow.com/questions/32138575/scapy-installation-fails-due-to-invalid-token

**Comment by kb1lqc** [comment]
OK @hdkmike I need some help. Mayb e @reillyeon can chip in too!

The TUN send test which right now I am aiming to put an IP packet onto the TUN adapter and check it. The code as it stands is here:
https://github.com/kb1lqc/faradayio/blob/faradaytun/tests/test_tun.py#L31


```
def test_tunSend():
    """Start a TUN adapter and send a SLIP message from IP"""
    # Start a TUN adapter
    faradayTUN = faraday.TunnelServer()
    # faradayTUN._tun.mtu = 100

    # Send a string throught the IP
    HOST = faradayTUN._tun.dstaddr
    PORT = 9999 #  Anything

    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    # time.sleep(60)
    s.connect((HOST,PORT))
    s.send(b'Hello, world')
    time.sleep(0.1)
    data = faradayTUN._tun.read(faradayTUN._tun.mtu)
    # print(type(repr(data)))
    print(data)
s.close()
```

This works by sending packets onto the TUN adapter, here's what wireshark picks up in hex:

`4500002845f440004011e0ce0a0000010a000002c3cd270f0014e09a48656c6c6f2c20776f726c64`

![image](https://user-images.githubusercontent.com/331540/34554212-acfdefe6-f0e0-11e7-8261-933cfe7fdbca.png)

Looking at just the "data" from wireshark it's clear that "Hello, world" get's through...

![image](https://user-images.githubusercontent.com/331540/34554260-e63e8644-f0e0-11e7-8d97-8f9573da9a9f.png)

However, when I use wireshark to "copy printable text" from the packet I get this:

```
E(E@@

'Hello, world
```
There's extra text and returns in there before Hello, world... Why?

Taking a DIFFERENT packet that was printed out from the unit test directly (not through wireshark) I get the following output in hex which I can use `scapy` to decode:

`a=IP(b"\x00\x00\x08\x00E\x00\x00(\xcc\x92@\x00@\x11Z0\n\x00\x00\x01\n\x00\x00\x02\xa0\x9d'\x0f\x00\x14\x03\xcbHello, world")`

```
###[ IP ]###
  version   = 0
  ihl       = 0
  tos       = 0x0
  len       = 2048
  id        = 17664
  flags     = 
  frag      = 40
  ttl       = 204
  proto     = 146
  chksum    = 0x3800
  src       = 64.17.90.48
  dst       = 10.0.0.1
  \options   \
   |###[ IP Option ]###
   |  copy_flag = 0
   |  optclass  = control
   |  option    = experimental_measurement
   |  length    = 0
   |  value     = ''
   |###[ IP Option End of Options List ]###
   |  copy_flag = 0
   |  optclass  = control
   |  option    = end_of_list
   |###[ IP Option Security ]###
   |  copy_flag = 0
   |  optclass  = control
   |  option    = security
   |  length    = 11
   |  security  = 0
   |  compartment= 0
   |  handling_restrictions= 0
   |  transmission_control_code= b'xxx'
###[ Raw ]###
     load      = b"\xa0\x9d'\x0f\x00\x14\x03\xcbHello, world"
```
Why is load showing the data preceding Hello, world???

Using bytes directly from wireshark shows a completely different and what appears to be irrelevant packet?

This also doesn't make sense as using `scapy` to decode the packet shows a completely different data
![image](https://user-images.githubusercontent.com/331540/34554456-d39e3808-f0e1-11e7-8cf4-2c874b01d18b.png)

Am I doing something massively wrong here? So far I don't think I need to do any linux routing and when I try it appears that the way I use `pytun` already performs some of the routing. Here's the output of `ip route show`:

`10.0.0.0/24 dev Faraday  proto kernel  scope link  src 10.0.0.1 `

**Comment by kb1lqc** [comment]
Whoa awesome thanks Reilly! Will give this a shot tonight.

---- On Thu, 04 Jan 2018 07:51:13 -0800 notifications@github.com wrote ----

Copying the printable text in Wireshark is copying all the printable text in the packet, which includes bytes from the IP header which happen to be printable ASCII.

scapy is showing a different packet because you are giving it a string of hexadecimal digits instead of the actual bytes of the packet. You can call,

IP(binascii.a2b_hex('4500002845f440004011e0ce0a0000010a000002c3cd270f0014e09a48656c6c6f2c20776f726c64'))

to convert the hexadecimal that Wireshark gives you back to the original bytes before parsing the packet.

**Comment by hdkmike** [comment]
Yup. @reillyeon  is completely correct here. 

As noted, you can take the `data` section of the packet `48656c6c6f2c20776f726c64` and convert from hex to ASCII and get `Hello, world` as expected.

**Comment by hdkmike** [comment]
Also, @kb1lqc , that routing is the "default" local subnet for the `Faraday` device and IP. It basically says "anything destined to 10.0.0.0 to 10.0.0.255, send it to the Faraday device originating from 10.0.0.1". Naturally, it will short circuit 10.0.0.1 (itself) to 127.0.0.0 on `lo`.

**Comment by hdkmike** [comment]
You need to dissect your packet.
1. Convert raw bytes to IP
2. Convert the payload of IP to protocol (UDP)
3. Get payload

```>>> t
b"\x00\x00\x08\x00E\x00\x00(p\xa3@\x00@\x11\xb6\x1f\n\x00\x00\x01\n\x00\x00\x02\x8b\x81'\x0f\x00\x14\x18\xe7Hello, world"
>>> ip_packet = IP(t)
>>> udp_packet = UDP(ip_packet.load)
>>> payload = udp_packet.load
>>> payload
b'Hello, world'
```

**Comment by kb1lqc** [comment]
OK lots of progress tonight talking to @hdkmike and using @reillyeon suggestion. One note before I wrap it up for the night.

Most seems to be working. However, I've noticed that I apparently get an IPV6 packet on the TUN network during the test which every now and then will cause my check for "Hello, world!" to fail since the IPV6 packet doesn't contain my string.
```
<bound method Packet.show of <IP  version=6 ihl=0 tos=0x0 len=0 id=8 flags=MF frag=6911 ttl=254 proto=128 chksum=0x0 src=0.0.0.0 dst=108.126.244.154 options=[<IPOption  copy_flag=1 optclass=debug option=31 length=213 value=b'\x8c.\xff\x02\x00\x00' |>] |<Padding  load=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x85\x00\xb0\x19\x00\x00\x00\x00' |>>>
```

**Comment by kb1lqc** [comment]
@hdkmike @reillyeon here's the IPV6 packet: 
![image](https://user-images.githubusercontent.com/331540/34600228-44ab6c5e-f1ab-11e7-80bb-7c81abe3c31a.png)

**Comment by kb1lqc** [comment]
Also noticed a bunch of IPV4 traffic even though my program should be in an infinite loop not using the TUN? Is this also network query traffic? Essentially noise?

![image](https://user-images.githubusercontent.com/331540/34600284-903a5d56-f1ab-11e7-9ace-0da3598ee21d.png)

**Comment by kb1lqc** [comment]
I simplified the TUN test this morning real quick by removing the SLIP code since it's not needed yet. Here's my simplified unit test that uses all printable ASCII values as message input for IP payload. I still have the IPV6 packet problem @reillyeon @hdkmike if you have thoughts?

https://github.com/kb1lqc/faradayio/blob/faradaytun/tests/test_tun.py#L33

![image](https://user-images.githubusercontent.com/331540/34615537-1e53e79a-f1ea-11e7-9b7c-4549e0f729c8.png)

It does pass periodically

![image](https://user-images.githubusercontent.com/331540/34615560-2d9865e6-f1ea-11e7-98e0-4d57d6d4ecbf.png)

**Comment by kb1lqc** [comment]
Interesting :warning: I noticed that when I my desktop is connected to a VPN the test appears to not fail due to IPV6 traffic...

**Comment by reillyeon** [comment]
You are probably getting traffic from other applications on the system trying to use the new network interface. For example, the packet you're looking at comes from Spotify. When checking for the expected packet you should parse it and filter on the particular UDP port you are using.

**Comment by kb1lqc** [comment]
I tried to implement an `asyncio` version of the TUN monitor which grabs data at the end of the tunnel to put over the serial port but it's not working out. I kept getting errors with `pytest` and `asyncio`...

`TypeError: A Future, a coroutine or an awaitable is required`

Even though I was using a coroutine in my `pytest` code and `pytest-asyncio`. I am going to use normal threads and move on.

**Comment by kb1lqc** [comment]
Also, I will do that @reillyeon

**Comment by kb1lqc** [comment]
So close @reillyeon and @hdkmike ! I now can send an IP packet over the TUN adapter, into a loopback serial port using a monitoring thread and also receive that loopback RX serial data from the same monitor thread (another issue if it should be two threads). The only missing piece is sending the received data from the loopback serial port over the TUN back to the IP/socket. 

Here's my received data from the serial port using `checkSerial()`:
https://github.com/kb1lqc/faradayio/blob/faradaytun/faradayio/faraday.py#L134
'''
message: b'\x00\x00\x08\x00E\x00\x00)\x1dp@\x00@\x11\tR\n\x00\x00\x01\n\x00\x00\x02\x89C\'\x0f\x00\x15\xfa"Hello, world!'
'''

Now, using the `.show()` function of `scapy` here's the packet received from the loopback serial port.
![image](https://user-images.githubusercontent.com/331540/34762660-5d4c2c9e-f59d-11e7-99ea-e38414ba4716.png)

Cool! @kb1lqd for awareness. 

Now I know for testing I need to swap the IP and ports or else Linux will not put the packet onto the stack to go back over the TUN. @hdkmike even did this with `dpkt` in https://github.com/hdkmike/simple-tuntap/blob/master/src/tunnel_easy.py#L19

However, when I use `scapy` values to swap data to mimic an echo:
```
packet = IP(item[4:])
src = packet.src
dst = packet.dst
sport = packet.sport
dport = packet.dport

packet.src = dst
packet.dst = src
packet.chksum = ''
```
This unfortunately doesn't create a valid packet. It get into the TUN!! However wireshark shows the source and destination IP's as blank and labels it a mis-formatted packet. Sorry I don't have a screenshot of it at this time. Any suggestion @hdkmike or @reillyeon ?

Thanks for the help so far. I'm so close and TUN is making way more sense.

**Comment by kb1lqc** [comment]
Is sport and dport one more layer down with UDP() formatting? It wasn't complaining about these when I directly grabbed them off of `packet` though I didn't print them.

**Comment by kb1lqc** [comment]
@hdkmike I realized we're using differnt pytun projects.

* You appear to be using https://github.com/Gawen/pytun
* I am using https://github.com/montag451/pytun

I'm inclined to think that you are using a better one. The `python-pytun` that I am using is not working very well on the writing into the TUN (equivalent to your send). However, when I try to install yours I get this:

```
(.venv) bryce@bryce-ubuntu:~/Documents/git/faradayio$ pip3 install pytun
Collecting pytun
  Using cached pytun-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-03ha346x/pytun/setup.py", line 11, in <module>
        import pytun
      File "/tmp/pip-build-03ha346x/pytun/pytun.py", line 115
        except IOError, e:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-03ha346x/pytun/
```

Tried googling but nothing. Is this module built for Python 3?

**Comment by kb1lqc** [comment]
#15 closed out the last of the tests needed to implement a TUN unit test and complete and end-to-end test (at least in parts). This ticket however doesn't below in the "Complete Initial Testing Suite" milestone so I'm removing it as well as the association to the test suite project.

**Comment by kb1lqc** [comment]
Closing as this ticket has served its purpose.

**Comment by alexandervlpl** [comment]
> @hdkmike I realized we're using differnt pytun projects.
> 
>     * You appear to be using https://github.com/Gawen/pytun
> 
>     * I am using https://github.com/montag451/pytun
> 
> 
> I'm inclined to think that you are using a better one. The `python-pytun` that I am using is not working very well on the writing into the TUN (equivalent to your send). However, when I try to install yours I get this:
> 
> ```
> (.venv) bryce@bryce-ubuntu:~/Documents/git/faradayio$ pip3 install pytun
> Collecting pytun
>   Using cached pytun-1.0.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-03ha346x/pytun/setup.py", line 11, in <module>
>         import pytun
>       File "/tmp/pip-build-03ha346x/pytun/pytun.py", line 115
>         except IOError, e:
>                       ^
>     SyntaxError: invalid syntax
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-03ha346x/pytun/
> ```
> 
> Tried googling but nothing. Is this module built for Python 3?

Did you ever resolve this pytun install issue?
