### ISSUE TITLE
Test Serial Interface to TUN

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/faradayio#15]
Implement a unit test which injects an IP packet onto the TUN tunnel to come out of a socket correctly.

* Should use `pytun` function `write()`
* Expect IP packet coming from the `Faraday` adapter to a specific IP/Port

**Comment by kb1lqc** [comment]
Ahh I have been trying to send IP packets using `tun.write()` from `pytun` but these were not working. they come into wireshark as unknown packets.

Actual code: `TUNMonitor._TUN._tun.write(packet.__bytes__())`

![image](https://user-images.githubusercontent.com/331540/34910117-6e68055c-f863-11e7-8cfa-ecd3298ce65a.png)

What I'm missing is the ethertype @hdkmike. Once I used `scapy` to send the pacekt with `sendp()` and per the [scapy cheat sheet](https://blogs.sans.org/pen-testing/files/2016/04/ScapyCheatSheet_v0.2.pdf) will add a custom ethertype. All works fine...

`sendp(packet,iface="Faraday")`

![image](https://user-images.githubusercontent.com/331540/34910168-3ed11760-f864-11e7-9080-709a3bc533a8.png)


Any way to add an ethertype without `scapy`?

**Comment by kb1lqc** [comment]
I can't seem to make the connection in `python-pytest` from testing the serial to TUN connection. My TUN has an IP of '10.0.0.1' and is running. Essentially, I want to `pytun.write()` a packet from '10.0.0.2' to '10.0.0.1' and have a way of testing what was sent.

Currently, I CAN see data traveling on the "Faraday" TUN and it is from '10.0.0.2' and destined for '10.0.0.1' which is the TUN adapter. However, _how do I grab the data from the TUN without WireShark_?

![image](https://user-images.githubusercontent.com/331540/35111446-239d430e-fc30-11e7-9080-88490aa9a8a5.png)

- Can I connect with a socket?
- Am I viewing this completely wrong and should I be using a second TUN for this?

I am just really confused as to what to expect data to do when it is written to the TUN. I completely get how opening a socket and sending it to an IP such as `10.0.0.2` will divert traffic through my TUN if its IP is `10.0.0.1` and the range it is responsible for is `10.0.0.0` through `10.0.0.255` and if I send that data with a socket connection I see it arrive in the TUN on wireshark and can `pytun.read()`. Yet I can't seem to wrap my head around where to obtain data written with `pytun.write()`... I apparently cannot just open a socket to the IP address.

@hdkmike @reillyeon @el-iso @alvarop

**Comment by herrold** [comment]
your tun0 device has a 'at a single IP netmask (255.255.255.255)
also it is in in a different C class (see: RFC1918) 
can you get it to be assigned to 10.0.0.2/24 ?

**Comment by kb1lqc** [comment]
`tun0` is a VPN not associated with my testing or Faraday. It's simply my VPN provider for normal internet access.

**Comment by herrold** [comment]
_please_ don't use pictures when addressing routing issues; it is so much easier to visualize with text pastes from:

    ifconfig,   # or
    ip a     

The command to use varies depending on your distribution, and the commands available, 

and

    netstat -rn     

That is: hypen Are Enn ... the non-serifed font which GH defaults to makes it visually hard to see,   or

    route -n 

> see: http://herrold.com/openvpn-multilink.html 

which is an old TUN device posting made long ago as to multi-leg OpenVPN

You said:

> it is from `10.0.0.2` and destined for `10.0.0.11`

but the tcpdump (wireshark) says it is destined to `10.0.0.1` ... 

wireshark is probably overkill until you have routing working -- raw tcpdump is much more concise:  see: 

1.  http://www.owlriver.com/tips/tcpdump-tech/
2.  http://www.owlriver.com/tips/trace-sendmail/

Really what I would look at, if sitting at a console are:

    # uname -a    # to figure out the distribution you are in
    # ip a              # to see the interfaces active
    # netstat -rn    # to see the routing tables

[convention: a command preceeded by #  is by root; $ is by a nonprivileged user]

One assumes, but it is not clear, that layer 2 bridge tables, and layer 3 iptables are not causing packet loss.  Also, more subtly, SELinux can play a hand here in packet transit denial

but let's see those three last mentioned in text form

**Comment by kb1lqc** [comment]
Thanks @herrold and I'll do better next time in providing more info! I had @hdkmike help out over the phone and we figured it out on Thursday evening.

## Proper Use of The `python-pytun` Package When Writing To TUN
Mike and I figured out that the following setup allows `nc` (Netcat) to receive packets from an IP on the computer. This is critical because it represents the receive path of data from Faraday -> Serial -> TUN -> IP. Also, I could NOT find any description online about proper operation other than basically assuming it should all work.

1. We setup a `SerialTestClass` instance so that the `Monitor` class can be used. We do not use this in our test at this time but need it to properly create a `Monitor` class instance.
2. Define source and destination addresses. Source = `10.0.0.1:9998` Destination = `10.0.0.2:9999`
3. Create a `faraday.Monitor()` class. It's important to note that the TUN address is `10.0.0.1`!
4. Use `scapy` to great an IP packet with a UDP packet enclosed inside. The IP destination = `10.0.0.1` (we're sending the packet to our TUN address) and the source address is `10.0.0.2`. Our UDP source port is `9998` and destination port is `9999`. It's important to note that the source and destination ports cannot be the same or else we see not traffic with `nc`! This packet is stored in the variable `srcPacket`. Also, we've added a note `Hello, world!` to the packet too.
5. Write the packet to the TUN with `TUNMonitor._TUN._tun.write()`. We add a standard EtherType of "\x00\x00\x08\x00" to the beginning of the packet as well.

When this is done we are repeatedly sending the packet to the TUN with a while loop. Using Netcat we can listen to the packet:

`sudo nc -l -u 10.0.0.1 9999`

This listens to `10.0.0.1` on port 9999 which is the IP address of our TUN. As currently setup, no other IP works. This is likely because we haven't told Linux that any routes exist and have specified only one IP address to the TUN.

**Comment by herrold** [comment]
no worries -- glad it got sorted out

In the interest of better bug reports, and in searching older ones, avoiding pictures of text, and using text, permits search engine indexing, and usually also permits clarifying just what is being looked at

73 de wb8sky

**Comment by kb1lqc** [comment]
I pushed my latest work to my branch [faradaytun](https://github.com/kb1lqc/faradayio/blob/faradaytun/tests/test_tun.py). The link should bring you to the test_tun.py file. 

As you can see [test_tunSlipSend()](https://github.com/kb1lqc/faradayio/blob/faradaytun/tests/test_tun.py#L85) sends a packet with scapy `sendp` and receives it over the serial loopback using the helper functions I wrote. It asserts that data is as expected along the way. However, it doesn't use the threads to do this since I was having some issues with that in pytest. I do end up utilizing a good amount of the code other than the `run()` thread. Note that I haven't quite figured out how to get an IP->TUN working in this test 😕 .

This is a bit manual but let me know if it doesn't make sense or you see a better way @reillyeon @hdkmike. I want to clean it up more tonight.
```
def test_tunSlipSend():
    """
    Test SLIP data sent over the TUN adapter and serial port.
    Start a TUN adapter and send data over it while a thread runs to receive
    data sent over the tunnel and promptly send it over a serial port which is
    running a serial loopback test. Ensures data at the end of the loopback
    test is valid when received over serial. This test does not cover serial
    to TUN/IP nor IP to TUN data validation.
    """
    # Create a test serial port
    serialPort = SerialTestClass()

    # Configure the TUN adapter and socket port we aim to use to send data on
    sourceHost = '10.0.0.1'  # IP of the TUN adapter
    sourcePort = 9998
    destHost = '10.0.0.2'
    destPort = 9999

    # Start the monitor
    TUNMonitor = faraday.Monitor(serialPort=serialPort, name="Faraday", addr=sourceHost, dstaddr=destHost)

    srcPacket = (IP(dst=destHost, src=sourceHost)/UDP(sport=sourcePort, dport=destPort)/"Hello, world!").__bytes__()

    # Use scapy to send packet over Faraday
    sendp(srcPacket,iface="Faraday")

    # Manually check TUN adapter for packets in the tunnel
    # This is necessary because the threads are not running
    while True:
        # Loop through packets until correct packet is returned
        packet = TUNMonitor.checkTUN()
        if packet:
            # Strip etherType off of IP packet
            ipPacketSerialTX = packet[4:]
            if IP(ipPacketSerialTX).dst == destHost:
                # Check that packet got through TUN without error
                break
    # Obtained IP packet to destination IP so check that it hasn't changed
    assert ipPacketSerialTX == srcPacket

    # Manually send IP packet over serial port including etherType.
    bytesSent = TUNMonitor.txSerial(packet)
    assert bytesSent is not None    #  We expect some data sent
    assert bytesSent > len(packet)  # We expect SLIP encoding to add bytes

    # Receive data over serial port and check packets for test IP packet
    rxBytes = TUNMonitor.rxSerial(TUNMonitor._TUN._tun.mtu)
    for item in rxBytes:
        ipPacketSerialRX = item[4:]
        # Iterate through packets and check for packet to destination IP
        if IP(ipPacketSerialRX).dst == destHost:
            # Found IP packet to destination so break from loop
            break

    # Check that the packet received over the serial loopback is the same as sent
    assert ipPacketSerialRX == ipPacketSerialTX
```

My last TUN test [test_serialToTUN](https://github.com/kb1lqc/faradayio/blob/faradaytun/tests/test_tun.py#L143) is simulating the act of having received a packet from the serial port and properly decoding SLIP from it to then take this assumption and `write()` data to the TUN and check for it on an IP address with a socket.

```
def test_serialToTUN():
    """
    Test serial port to TUN link. Don't need a serial port but just assume that
    an IP packet was received from the serial port and properly decoded with
    SLIP. Send it to the TUN and verify that the IP:PORT receives the message.
    """
    # Create a test serial port for TUN Monitor class. Won't be used.
    serialPort = SerialTestClass()

    # Configure TUN IP:PORT and IP Packet source IP:PORT parameters for test
    sourceAddress = '10.0.0.2'
    sourcePort = 9998
    tunAddress = '10.0.0.1'
    tunPort = 9999

    # Start a TUN Monitor class
    TUNMonitor = faraday.Monitor(serialPort=serialPort, name="Faraday",addr=tunAddress,dstaddr=sourceAddress)

    # Open a socket for UDP packets and bind it to the TUN address:port
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(('10.0.0.1', 9999))

    # Create simple IP packet with message. Send to TUN address:port
    message = bytes("Hello, World! {0}".format(time.time()),"utf-8")
    etherType = b"\x00\x00\x08\x00"
    packet = etherType + (IP(dst=tunAddress, src=sourceAddress)/UDP(sport=sourcePort, dport=tunPort)/message).__bytes__()

    # Write a simple message over the TUN, no need for checker thread
    TUNMonitor._TUN._tun.write(packet)

    # Receive data from the socket bound to the TUN address:port
    data, address = s.recvfrom(4096)

    # Check that data written to TUN matches data received from socket
    assert data == message

    # Close the socket
    s.close()
```

Any comments welcome! I'd love to do this test in one fell swoop but that is a bit tougher than I hoped with the loopback and having to likely swap IP:port destinations.

**Comment by kb1lqc** [comment]
As shown on https://github.com/kb1lqc/faradayio/blob/develop/tests/test_tun.py#L134 I finally achieved an IP Packet written to TUN coming out of a socket.

```
def test_serialToTUN():
    """
    Test serial port to TUN link. Don't need a serial port but just assume that
    an IP packet was received from the serial port and properly decoded with
    SLIP. Send it to the TUN and verify that the IP:PORT receives the message.
    """
    # Create a test serial port for TUN Monitor class. Won't be used.
    serialPort = SerialTestClass()

    # Configure TUN IP:PORT and IP Packet source IP:PORT parameters for test
    sourceAddress = '10.0.0.2'
    sourcePort = 9998
    tunAddress = '10.0.0.1'
    tunPort = 9999

    # Start a TUN Monitor class
    TUNMonitor = faraday.Monitor(serialPort=serialPort,
                                 name="Faraday",
                                 addr=tunAddress,
                                 mtu=1500)

    # Open a socket for UDP packets and bind it to the TUN address:port
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(('10.0.0.1', 9999))

    # Create simple IP packet with message. Send to TUN address:port
    message = bytes("Hello, World! {0}".format(time.time()), "utf-8")
    etherType = b"\x00\x00\x08\x00"
    packet = etherType + (IP(dst=tunAddress,
                             src=sourceAddress) /
                          UDP(sport=sourcePort,
                              dport=tunPort)/message).__bytes__()

    # Write a simple message over the TUN, no need for checker thread
    TUNMonitor._TUN._tun.write(packet)

    # Receive data from the socket bound to the TUN address:port
    data, address = s.recvfrom(4096)

    # Check that data written to TUN matches data received from socket
    assert data == message

    # Close the socket
    s.close()
```

The tricks that ended up being critical:
- Send the IP packet to the TUN interface IP
- Open up a UDP socket server and bind it to the TUN IP address
- Write the IP packet to the TUN interface (destined for the TUN IP, from another IP on the same network)
- Source and destination ports apparently need to be different.
- Read the data off the socket opened

**Comment by kb1lqc** [comment]
Per https://travis-ci.org/kb1lqc/faradayio/builds/334260266 we have a passing test in the `develop` branch that uses the correct `serialToTUN()` code. While there are probably improvements that will be made this is a great start. The code is correctly writing and IP packet to the TUN as if it came from another computer/radio and that packet is being received over a socket connection on the local computer.
