### ISSUE TITLE
pytun not installing with virtualenv Ubuntu 16.04

### ISSUE THREAD

**Issue by lqdev** [FaradayRF/faradayio#28]
Tried to follow the instructions on the [Working With Python3 Virtual Environments](https://github.com/FaradayRF/faradayio/wiki/Working-With-Python3-Virtual-Environments) wiki page and ran into issues in the installation of the `Requirements.txt` file when trying to install the `pytun` package. Issue may be caused by `Python.h` header file. I am running Ubuntu 16.04. Attached was the output from the installation attempt

[output.txt](https://github.com/FaradayRF/faradayio/files/1670667/output.txt)

**Comment by kb1lqc** [comment]
Ahh @lqdev due to the heavy first round of development you will want to work with the `develop` branch. Sorry about that. I incorrectly assumed you'd see the branches versus `master`. My bad! I will be pulling them in shortly to `master`.

**Comment by kb1lqc** [comment]
Also `develop` is in my personal repo at this time as my workflow is to fork to my own repo and use PR's to pull it in.

https://github.com/kb1lqc/faradayio/tree/develop

**Comment by kb1lqc** [comment]
@lqdev Please try again as I've pulled in #34 which places the new code on our FaradayRF/faradayio master branch.

**Comment by lqdev** [comment]
It worked. It happened to be an issue of not having python-dev modules installed. This one can be closed.

**Comment by kb1lqc** [comment]
Thanks @lqdev !
